name: autockt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - backcall=0.1.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - certifi=2018.8.24
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.3.2
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.4
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.6.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxml2=2.9.9
  - markupsafe=1.0
  - matplotlib=3.0.0
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - opencv=3.4.2
  - openssl=1.0.2t
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - pixman=0.38.0
  - prompt_toolkit=1.0.15
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2019.2
  - qt=5.9.6
  - readline=7.0
  - scipy=1.1.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - sqlite=3.29.0
  - tensorflow-base=1.10.0
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - werkzeug=0.16.0
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - filelock==3.0.12
    - flatbuffers==1.11
    - funcsigs==1.0.2
    - future==0.17.1
    - grpcio==1.24.0
    - gym==0.10.5
    - idna==2.8
    - importlib-metadata==0.23
    - markdown==3.1.1
    - more-itertools==7.2.0
    - numpy==1.16.4
    - packaging==19.2
    - pathlib2==2.3.5
    - pluggy==0.13.0
    - protobuf==3.9.2
    - py==1.8.0
    - pyglet==1.4.4
    - pytest==5.2.0
    - pyyaml==5.1.2
    - ray==0.6.3
    - redis==3.3.8
    - requests==2.22.0
    - setuptools==39.1.0
    - six==1.12.0
    - tensorboard==1.10.0
    - tensorflow==1.10.1
    - termcolor==1.1.0
    - urllib3==1.25.6
    - wcwidth==0.1.7
    - zipp==0.6.0
prefix: /users/ksettaluri6/anaconda3/envs/autockt

